import Config

dev_github_private_key =
  Path.expand("../local/robine-ci.2026-08-09.private-key.pem", __DIR__)
  |> File.read()
  |> case do
    {:ok, contents} -> contents
    {:error, _reason} -> ""
  end

# Stable local-only credential for the first-run setup screen. Production
# continues to require ROBINE_BOOTSTRAP_TOKEN at runtime.
config :robine,
  public_url: "https://ci-dev.base59.dev",
  bootstrap_token_hash: :crypto.hash(:sha256, "dev-bootstrap-token"),
  bootstrap_expires_at: ~U[2100-01-01 00:00:00Z],
  github_app_id: "4536638",
  dev_setup_form_defaults: %{
    "token" => "dev-bootstrap-token",
    "email" => "admin@robine.local",
    "password" => "password1234"
  },
  dev_github_private_key_form_default: dev_github_private_key,
  dev_github_webhook_secret_form_default: "veryverysecret"

# Fixed development-only key. Runtime environment keys still override this value.
config :robine, :secret_keyring,
  current_version: 1,
  keys: %{1 => :binary.copy(<<42>>, 32)}

# Configure your database
config :robine, Robine.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "robine_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :robine, RobineWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "AJghjXFmuZQ9CObUoj5lN81zLUGZuWnYG+MrgOTwYRFYsBWePT4VcsLUHiYNZr0D",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:robine, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:robine, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :robine, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
