[package]
name = "robine-execution"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
flate2.workspace = true
robine-source = { path = "../robine-source" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tar.workspace = true
tokio.workspace = true
uuid.workspace = true
zeroize.workspace = true

[lints]
workspace = true
